version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: restaurant_reservation_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: user_service.py
    depends_on:
      - db

  reservation_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5002:5000"
    environment:
      FLASK_APP: reservation_service.py
    depends_on:
      - db

volumes:
  pgdata:
